source "https://rubygems.org"

gem "sinatra"
gem "activerecord"
gem "sinatra-activerecord"
gem "pg"
gem "rest-client"
gem "foreman"
gem "resque"
gem "shotgun"
gem "rake"
gem "dropbox_api"
gem "json"
gem "rubysl-ostruct"
